# Generated by Django 5.2.5 on 2025-08-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_initial"),
        ("review", "0001_initial"),
        ("trend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="thumbnails/")),
                ("isUserMade", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isLiked", models.BooleanField(default=False)),
                ("firstContent", models.TextField()),
                ("secondContent", models.TextField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("keywords", models.ManyToManyField(to="trend.keyword")),
                (
                    "review_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletterItem",
                        to="review.reviewanalysis",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="newsletterItem", to="main.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="newsletterItem", to="main.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
