# Generated by Django 5.2.5 on 2025-08-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profileName', models.CharField(max_length=50)),
                ('profilePhoneNumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('kakaoStore', models.IntegerField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('isWillingCollaborate', models.BooleanField(default=False)),
                ('storeContent', models.TextField(blank=True)),
                ('menu', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('visitor', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('newsContent', models.TextField()),
                ('keywordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='trend.keyword')),
            ],
        ),
    ]
