# Generated by Django 4.2.23 on 2025-08-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        ("review", "0001_initial"),
        ("trend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="keywordId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="newsletters", to="trend.keyword"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="reviewAnalysisId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="newsletters", to="review.reviewanalysis"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="storeId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="newsletters", to="main.store"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="newsletters", to="main.profile"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="main.store",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="main.type"
            ),
        ),
    ]
