# Generated by Django 5.2.5 on 2025-08-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='reviewAnalysisId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='review.reviewanalysis'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='main.profile'),
        ),
        migrations.AddField(
            model_name='store',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='main.profile'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='storeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='main.store'),
        ),
    ]
