# Generated by Django 5.2.5 on 2025-08-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_type_remove_store_kakaostore_store_kakaoplaceid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="is_foreign",
        ),
        migrations.AddField(
            model_name="visitor",
            name="isForeign",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("searchTerm", models.CharField(max_length=100)),
                ("searchDate", models.DateTimeField(auto_now_add=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="searches", to="main.profile"
                    ),
                ),
            ],
        ),
    ]
