# Generated by Django 4.2.23 on 2025-08-17 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_visitor_is_foreign_visitor_isforeign_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='search',
            name='searchDate',
        ),
        migrations.RemoveField(
            model_name='search',
            name='searchTerm',
        ),
        migrations.RemoveField(
            model_name='store',
            name='isWillingCollaborate',
        ),
        migrations.RemoveField(
            model_name='store',
            name='kakaoPlaceId',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storeContent',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='isForeign',
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='main.store'),
        ),
        migrations.AddField(
            model_name='search',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_willing_collaborate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='kakao_place_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='age_group',
            field=models.IntegerField(choices=[(0, '청소년'), (1, '청년'), (2, '중년'), (3, '노년')], default=2),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_foreign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='main.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('M', '남'), ('F', '여'), ('O', '기타')], max_length=1),
        ),
    ]
