# Generated by Django 4.2.23 on 2025-08-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_menu_name_menu_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="is_willing_collaborate",
            new_name="isWillingCollaborate",
        ),
    ]
