# Generated by Django 4.2.23 on 2025-08-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_is_willing_collaborate_store_iswillingcollaborate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="kakao_place_id",
            new_name="kakaoPlaceId",
        ),
    ]
