# Generated by Django 4.2.23 on 2025-08-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_kakao_place_id_store_kakaoplaceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="storeNumber",
            field=models.TextField(blank=True, null=True),
        ),
    ]
