# Generated by Django 5.2.5 on 2025-08-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                ("reviewerId", models.AutoField(primary_key=True, serialize=False)),
                ("follower", models.IntegerField(blank=True, null=True)),
                ("reviewCount", models.IntegerField(blank=True, null=True)),
                ("reviewAvg", models.FloatField(blank=True, null=True)),
                ("reviewerName", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewAnalysis",
            fields=[
                ("reviewAnalysisId", models.AutoField(primary_key=True, serialize=False)),
                ("storeName", models.CharField(blank=True, default="", max_length=255)),
                ("goodPoint", models.TextField(blank=True, default="")),
                ("badPoint", models.TextField(blank=True, default="")),
                ("goodPercentage", models.FloatField(default=50.0)),
                ("middlePercentage", models.FloatField(default=0.0)),
                ("badPercentage", models.FloatField(default=50.0)),
                ("analysisKeyword", models.TextField(blank=True, default="")),
                ("analysisProblem", models.TextField(blank=True, default="")),
                ("analysisSolution", models.TextField(blank=True, default="")),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True, null=True)),
                (
                    "storeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review_analysis", to="main.store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("reviewId", models.AutoField(primary_key=True, serialize=False)),
                ("reviewContent", models.TextField()),
                ("reviewDate", models.DateTimeField()),
                ("reviewRate", models.IntegerField()),
                (
                    "storeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="main.store"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="review.reviewer"
                    ),
                ),
            ],
        ),
    ]
