# Generated by Django 5.2.5 on 2025-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewanalysis",
            name="analysisContent",
        ),
        migrations.RemoveField(
            model_name="reviewanalysis",
            name="reviewId",
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="analysisKeyword",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="analysisProblem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="analysisSolution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="badPercentage",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="badPoint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="goodPercentage",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="goodPoint",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="middlePercentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="storeName",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reviewanalysis",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
