# Generated by Django 5.2.5 on 2025-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewanalysis",
            name="term",
            field=models.IntegerField(default=0),
        ),
    ]
