# Generated by Django 5.2.5 on 2025-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_remove_reviewanalysis_analysiscontent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewer",
            name="reviewerNamer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="follower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="reviewAvg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewer",
            name="reviewCount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
