# Generated by Django 5.2.5 on 2025-08-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_reviewer_reviewernamer_alter_reviewer_follower_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewer",
            old_name="reviewerNamer",
            new_name="reviewerName",
        ),
    ]
