# Generated by Django 5.2.5 on 2025-08-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWordImageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWordName', models.CharField(max_length=50)),
                ('isImage', models.BooleanField(default=False)),
                ('keyWordCreatedAt', models.DateField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='trend.keywordimage')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='trend.trend')),
            ],
        ),
    ]
