# Generated by Django 5.2.5 on 2025-08-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trendData", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keywordName", models.CharField(max_length=50)),
                ("keywordImageUrl", models.URLField(blank=True, null=True)),
                ("isImage", models.BooleanField(default=False)),
                ("keywordCreatedAt", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "isCreatedByUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="main.store",
                    ),
                ),
                (
                    "trend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="trend.trend",
                    ),
                ),
            ],
        ),
    ]
