# Generated by Django 4.2.23 on 2025-08-20 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trend",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
