# Generated by Django 4.2.23 on 2025-08-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0002_trend_createdat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="keyWordCreatedAt",
            new_name="keywordCreatedAt",
        ),
        migrations.RenameField(
            model_name="keywordimage",
            old_name="keyWordImageUrl",
            new_name="keywordImageUrl",
        ),
    ]
