# Generated by Django 4.2.23 on 2025-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0003_rename_keywordcreatedat_keyword_keywordcreatedat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="keyWordName",
            new_name="keywordName",
        ),
    ]
