# Generated by Django 4.2.23 on 2025-08-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_is_willing_collaborate_store_iswillingcollaborate"),
        ("trend", "0004_rename_keywordname_keyword_keywordname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="trend.keywordimage"
            ),
        ),
        migrations.CreateModel(
            name="KeywordByUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keywordName", models.CharField(max_length=50)),
                ("isImage", models.BooleanField(default=False)),
                ("keywordCreatedAt", models.DateField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="trend.keywordimage"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="keywords", to="main.store"
                    ),
                ),
            ],
        ),
    ]
