# Generated by Django 4.2.23 on 2025-08-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0005_alter_keyword_image_keywordbyuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="image",
        ),
        migrations.AddField(
            model_name="keyword",
            name="isCreatedByUser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="keyword",
            name="keywordImageUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="KeywordByUser",
        ),
        migrations.DeleteModel(
            name="KeyWordImage",
        ),
    ]
