# Generated by Django 4.2.23 on 2025-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0006_remove_keyword_image_keyword_iscreatedbyuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
