# Generated by Django 4.2.23 on 2025-08-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trend", "0007_keyword_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="trend",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="keywords", to="trend.trend"
            ),
        ),
    ]
