# Generated by Django 4.2.23 on 2025-08-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_is_willing_collaborate_store_iswillingcollaborate"),
        ("trend", "0008_alter_keyword_trend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="isCreatedByUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="main.store",
            ),
        ),
    ]
