# Generated by Django 5.2.5 on 2025-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collaborate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("initialMessage", models.TextField(blank=True, null=True)),
                ("requestMemo", models.TextField(blank=True, null=True)),
                ("responseMemo", models.TextField(blank=True, null=True)),
                ("isAccepted", models.IntegerField(choices=[(0, "대기"), (1, "수락"), (2, "거절")], default=0)),
                ("requestCreatedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
