# Generated by Django 4.2.23 on 2025-08-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("initialMessage", models.TextField(blank=True, null=True)),
                ("requestMemo", models.TextField(blank=True, null=True)),
                ("responseMemo", models.TextField(blank=True, null=True)),
                ("isAccepted", models.IntegerField(choices=[(0, "대기"), (1, "수락"), (2, "거절")], default=0)),
                ("requestCreatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "requestStore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="requestCollaborate", to="main.store"
                    ),
                ),
                (
                    "responseStore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="responseCollaborate", to="main.store"
                    ),
                ),
            ],
        ),
    ]
