# Generated by Django 5.2.5 on 2025-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAccepted', models.IntegerField(default=0)),
                ('requestCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(blank=True)),
            ],
        ),
    ]
