# Generated by Django 5.2.5 on 2025-08-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborate',
            name='requestStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestCollaborate', to='main.store'),
        ),
        migrations.AddField(
            model_name='collaborate',
            name='responseStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseCollaborate', to='main.store'),
        ),
    ]
