# Generated by Django 5.2.5 on 2025-08-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaboration", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborate",
            name="requestStore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="requestCollaborate", to="main.store"
            ),
        ),
        migrations.AddField(
            model_name="collaborate",
            name="responseStore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="responseCollaborate", to="main.store"
            ),
        ),
        migrations.AddConstraint(
            model_name="collaborate",
            constraint=models.CheckConstraint(
                condition=models.Q(("requestStore", models.F("responseStore")), _negated=True),
                name="collab_diff_stores",
            ),
        ),
        migrations.AddConstraint(
            model_name="collaborate",
            constraint=models.CheckConstraint(
                condition=models.Q(("isAccepted__in", [0, 1, 2])), name="collab_status_012_only"
            ),
        ),
    ]
