# Generated by Django 4.2.23 on 2025-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborate",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
