# Generated by Django 4.2.23 on 2025-08-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0003_collaborate_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collaborate",
            old_name="content",
            new_name="initialMessage",
        ),
        migrations.AddField(
            model_name="collaborate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="collaborate",
            name="requestMemo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collaborate",
            name="responseMemo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collaborate",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="collaborate",
            name="isAccepted",
            field=models.IntegerField(choices=[(0, "대기"), (1, "수락"), (2, "거절")], default=0),
        ),
        migrations.AddConstraint(
            model_name="collaborate",
            constraint=models.CheckConstraint(
                check=models.Q(("requestStore", models.F("responseStore")), _negated=True), name="collab_diff_stores"
            ),
        ),
        migrations.AddConstraint(
            model_name="collaborate",
            constraint=models.CheckConstraint(
                check=models.Q(("isAccepted__in", [0, 1, 2])), name="collab_status_012_only"
            ),
        ),
    ]
